CHANGELOG.md, README.md, example/.gitignore, example/pubspec.lock, lib/property_widgets.dart, lib/widget.dart, pubspec.yaml
=> New layout and web support

README.md, pubspec.yaml
Example in readme doesn't compile with the latest version.
=> Fix example in README.md

CHANGELOG.md, example/pubspec.lock, lib/widget.dart
=> Adding some improvements from ideas taken on the demo app for Flame

example/lib/main.dart, lib/property_widgets.dart, lib/widget.dart
> Add code format based on "Pass static analysis" scores' feedback.
* I didn't change anything about logic, just formatting.
=> chore(add-code-formart): Add missing format according to dartfmt

example/lib/main.dart, example/pubspec.lock, lib/property_widgets.dart, lib/story.dart, lib/widget.dart, pubspec.lock, pubspec.yaml
> Add support to color properties
=> feat(color-property): Add color property support

example/pubspec.lock, lib/property_widgets/edge_insets_property.dart
In mobile version:
- Labels `Left Top Right Bottom` to `L T R B`
- Message to use the same value to all edge insets to fit the screen
- Parsed to the values to int
=> In mobile version, adjusting layout do fit the screen

example/pubspec.lock, example/pubspec.yaml, lib/property_widgets/bool_property.dart, lib/property_widgets/border_radius_property.dart, lib/property_widgets/color_property.dart, lib/property_widgets/edge_insets_property.dart, lib/property_widgets/list_property.dart, lib/property_widgets/number_property.dart, lib/property_widgets/text_property.dart, lib/property_widgets/widgets/property_4_integer_form.dart, lib/property_widgets/widgets/property_dialog.dart, lib/property_widgets/widgets/property_scaffold.dart, lib/story.dart, lib/widget.dart, pubspec.lock, pubspec.yaml
The code has been migrated to null safety.
However, `flutter_colorpicker` has not released the null safety compatible version yet. However, it has null safety support in the main branch. Thus we need to use a dependency override for now.
=> 🏷 Null safety support

CHANGELOG.md, lib/src/widgets/property_widgets/list_property.dart
Fix text overflow on list properties.
=> Text wrap on DropdownButton from ListPropertyWidget

CHANGELOG.md, README.md, example/lib/main.dart, example/pubspec.lock, lib/src/widgets/widget.dart
=> Adding useSafeAreaPreview

example/pubspec.lock, example/pubspec.yaml, lib/src/story.dart, lib/src/widgets/icon.dart, lib/src/widgets/link.dart, lib/src/widgets/properties_container.dart, lib/src/widgets/property_widgets/bool_property.dart, lib/src/widgets/property_widgets/border_radius_property.dart, lib/src/widgets/property_widgets/color_property.dart, lib/src/widgets/property_widgets/edge_insets_property.dart, lib/src/widgets/property_widgets/list_property.dart, lib/src/widgets/property_widgets/number_property.dart, lib/src/widgets/property_widgets/text_property.dart, lib/src/widgets/property_widgets/widgets/property_4_integer_form.dart, lib/src/widgets/property_widgets/widgets/property_dialog.dart, lib/src/widgets/property_widgets/widgets/property_scaffold.dart, lib/src/widgets/side_bar_panel.dart, lib/src/widgets/stories_list.dart, lib/src/widgets/widget.dart, pubspec.lock, pubspec.yaml
This PR re migrates Dashbook to support null safe. We did it again because the null safe branch diverged too much from the code on master, so it was easier to just redo it.
=> Re migrating Dashbook to null safety

CHANGELOG.md, example/lib/main.dart, example/lib/main_without_theme.dart, example/lib/stories.dart, lib/src/widgets/widget.dart
_currentTheme couldn't be late as null themes is a valid option.
=> Fixing null theme

CHANGELOG.md, lib/src/widgets/side_bar_panel.dart, lib/src/widgets/stories_list.dart
Fixes #40 
https://user-images.githubusercontent.com/835641/113481285-0882c280-946f-11eb-9557-a0bf6db5d6b3.mov
=> Persisting scroll and item collapse on the stories list

CHANGELOG.md, lib/src/platform_utils/mobile.dart, lib/src/platform_utils/platform_utils.dart, lib/src/platform_utils/unsupported.dart, lib/src/platform_utils/web.dart, lib/src/story.dart, lib/src/widgets/widget.dart
Solves #32 
https://user-images.githubusercontent.com/835641/113485899-6b338880-9486-11eb-8dc0-54bf748e7926.mov
=> Adding share feature for web

CHANGELOG.md, example/pubspec.lock, lib/src/platform_utils/web.dart, lib/src/preferences.dart, lib/src/story_util.dart, lib/src/widgets/stories_list.dart, lib/src/widgets/widget.dart, pubspec.lock, pubspec.yaml
Adding a bookmark handler, when a chapter is bookmarked, next time that Dashbook is accessed (like a reload for example) the bookmarked chapter will be initially open.
Quite useful when developing new widgets and you need to keep use hot restart.
=> Adding bookmark handler

CHANGELOG.md, example/lib/text_story.dart, lib/src/story.dart, lib/src/widgets/properties_container.dart, lib/src/widgets/property_widgets/options_property.dart, lib/src/widgets/property_widgets/properties.dart, test/properties/options_property_test.dart
Solves #53 
https://user-images.githubusercontent.com/835641/123497514-3b6acb80-d604-11eb-9d4c-2e75f6d9dbb9.mov
=> Adding options list

.gitignore, CHANGELOG.md, lib/src/widgets/keys.dart, lib/src/widgets/side_bar_panel.dart, lib/src/widgets/stories_list.dart, lib/src/widgets/widget.dart, test/widget/stories_list_test.dart
https://user-images.githubusercontent.com/835641/123711833-86c0ec00-d847-11eb-82e9-aa3b2dba4367.mov
=> Adding Stories filter

README.md
Hi amazing developers,
A minor point: the version of the `dashbook` in `README.md` is out of date.
Thank you.
=> docs: Fixed dependency version

CHANGELOG.md, README.md, lib/dashbook.dart, lib/src/widgets/widget.dart, test/widget/widget_test.dart
Adds a callback to `Dashbook` that is called everytime a new chapter is selected
=> feat: adding onChangeChapter to Dashbook

CHANGELOG.md, README.md, example/lib/stories.dart, lib/generated_plugin_registrant.dart, lib/src/story.dart, lib/src/widgets/actions_container.dart, lib/src/widgets/keys.dart, lib/src/widgets/widget.dart, test/widget/actions_list_test.dart
Adds a new API called `actions` to enable methods to called from Dashbooks UI.
=> feat: adding actions API

example/lib/properties/date_time_property.dart, example/lib/stories.dart, example/pubspec.yaml, lib/dashbook.dart, lib/src/story.dart, lib/src/widgets/properties_container.dart, lib/src/widgets/property_widgets/bool_property.dart, lib/src/widgets/property_widgets/border_radius_property.dart, lib/src/widgets/property_widgets/color_property.dart, lib/src/widgets/property_widgets/edge_insets_property.dart, lib/src/widgets/property_widgets/list_property.dart, lib/src/widgets/property_widgets/number_property.dart, lib/src/widgets/property_widgets/options_property.dart, lib/src/widgets/property_widgets/text_property.dart, lib/src/widgets/property_widgets/widgets/property_scaffold.dart, pubspec.yaml, test/properties/custom_propertis/custom_property_anonymous_builder_test.dart, test/properties/custom_propertis/custom_property_test.dart
This PR adds support for creating and adding custom property types.
=> feat: Custom property types

lib/src/widgets/preview_container.dart, lib/src/widgets/select_device/custom_device.dart, lib/src/widgets/select_device/device_dialog.dart, lib/src/widgets/select_device/device_settings.dart, lib/src/widgets/select_device/select_device.dart, lib/src/widgets/widget.dart, test/widget/device_dialog_test.dart, test/widget/widget_test.dart
=> feat: Text scale factor

bricks/dashbook_gallery/CHANGELOG.md, bricks/dashbook_gallery/LICENSE, bricks/dashbook_gallery/brick.yaml
Adding some missing information required to publish the brick into brick hub
=> fix: brick publishment requirements

README.md
This way we dont need to update the readme every time a new release comes about
=> docs: update installatiion 

lib/src/widgets/widget.dart
If you're app is not using english, supportedLocales properties from MaterialApp is neeeded
=> Handle supported locales properties
